name: "Build"
on:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.4.0
    - uses: cachix/install-nix-action@v15
    - run: nix develop --command make ci-build
    - run: git config --global user.email "cameron@11bitsoftware.com"
    - run: git config --global user.name "pages-updater"
    - run: git clone https://github.com/11bitsoftware/11-bit-software-website-pages.git pages
    - run: rm -f pages/* && cp build/* pages/
    - run: cd pages && git add . && git commit -am "update pages $(date)" && git push
